/**
  ******************************************************************************
  * @file    bluenrg_lp_cmd_if.c
  * @author  AMS - RF Application team
  * @date    25 February 2022
  * @brief   Autogenerated files, do not edit!!
  ******************************************************************************
  * @attention
  *
  * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
  * WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE
  * TIME. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY
  * DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING
  * FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE
  * CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
  *
  * <h2><center>&copy; COPYRIGHT STMicroelectronics</center></h2>
  ******************************************************************************
  */
#include "bluenrg_lp_stack.h"
#include "stack_user_cfg.h"
#include "bluenrg_lp_api.h"
#include "compiler.h"
#include "rf_driver_hal_vtimer.h"
#include "bleplat.h"
#include "nvm_db.h"
#include "gap_profile.h"
#include "pka_manager.h"
#include "rng_manager.h"
#include "aes_manager.h"
#include "ble_controller.h"

SECTION(".cmd_call_table")
REQUIRED(void * const cmd_call_table[]) = {
  (void *) BLE_STACK_Init,
  (void *) BLE_STACK_Tick,
  (void *) BLE_STACK_SleepCheck,
  (void *) BLE_STACK_RadioHandler,
  (void *) BLE_STACK_ReadNextRadioActivity,
  (void *) Gap_profile_set_dev_name,
  (void *) AESMGR_Init,
  (void *) AESMGR_Encrypt,
  (void *) BLECNTR_InitGlobal,
  (void *) BLECNTR_GlobSetDefaultAntennaid,
  (void *) PKAMGR_Init,
  (void *) PKAMGR_PowerSaveLevelCheck,
  (void *) PKA_IRQHandler,
  (void *) RNGMGR_Init,
  (void *) HAL_VTIMER_Init,
  (void *) HAL_VTIMER_Tick,
  (void *) HAL_VTIMER_StartTimerMs,
  (void *) HAL_VTIMER_StopTimer,
  (void *) HAL_VTIMER_GetCurrentSysTime,
  (void *) HAL_VTIMER_AddSysTimeMs,
  (void *) HAL_VTIMER_DiffSysTimeMs,
  (void *) HAL_VTIMER_StartTimerSysTime,
  (void *) HAL_VTIMER_ExpiryTime,
  (void *) HAL_VTIMER_PowerSaveLevelCheck,
  (void *) HAL_VTIMER_TimeoutCallback,
  (void *) HAL_VTIMER_WakeUpCallback,
  (void *) HAL_VTIMER_RadioTimerIsr,
  (void *) HAL_VTIMER_EndOfRadioActivityIsr,
  (void *) BLEPLAT_Init,
  (void *) NVMDB_Tick,
  (void *) hci_disconnect,
  (void *) hci_read_remote_version_information,
  (void *) hci_set_event_mask,
  (void *) hci_read_transmit_power_level,
  (void *) hci_set_event_mask_page_2,
  (void *) hci_read_authenticated_payload_timeout,
  (void *) hci_write_authenticated_payload_timeout,
  (void *) hci_read_local_version_information,
  (void *) hci_read_local_supported_commands,
  (void *) hci_read_local_supported_features,
  (void *) hci_read_bd_addr,
  (void *) hci_read_rssi,
  (void *) hci_le_set_event_mask,
  (void *) hci_le_read_buffer_size,
  (void *) hci_le_read_local_supported_features,
  (void *) hci_le_set_random_address,
  (void *) hci_le_set_advertising_parameters,
  (void *) hci_le_read_advertising_channel_tx_power,
  (void *) hci_le_set_advertising_enable,
#if (CONTROLLER_MASTER_ENABLED == 1)
  (void *) hci_le_set_scan_parameters,
  (void *) hci_le_set_scan_enable,
  (void *) hci_le_create_connection,
  (void *) hci_le_create_connection_cancel,
#endif
  (void *) hci_le_read_white_list_size,
  (void *) hci_le_clear_white_list,
  (void *) hci_le_add_device_to_white_list,
  (void *) hci_le_remove_device_from_white_list,
#if (CONTROLLER_MASTER_ENABLED == 1)
  (void *) hci_le_connection_update,
#endif
#if (CONTROLLER_MASTER_ENABLED == 1) ||\
    (CONTROLLER_EXT_ADV_SCAN_ENABLED == 1)
  (void *) hci_le_set_host_channel_classification,
#endif
  (void *) hci_le_read_channel_map,
  (void *) hci_le_read_remote_used_features,
  (void *) hci_le_encrypt,
  (void *) hci_le_rand,
#if (CONTROLLER_MASTER_ENABLED == 1)
  (void *) hci_le_start_encryption,
#endif
  (void *) hci_le_long_term_key_request_reply,
  (void *) hci_le_long_term_key_requested_negative_reply,
  (void *) hci_le_read_supported_states,
  (void *) hci_le_receiver_test,
  (void *) hci_le_transmitter_test,
  (void *) hci_le_test_end,
#if (CONTROLLER_DATA_LENGTH_EXTENSION_ENABLED == 1)
  (void *) hci_le_set_data_length,
  (void *) hci_le_read_suggested_default_data_length,
  (void *) hci_le_write_suggested_default_data_length,
#endif
#if (SECURE_CONNECTIONS_ENABLED == 1)
  (void *) hci_le_read_local_p256_public_key,
  (void *) hci_le_generate_dhkey,
#endif
#if (CONTROLLER_PRIVACY_ENABLED == 1)
  (void *) hci_le_add_device_to_resolving_list,
  (void *) hci_le_remove_device_from_resolving_list,
  (void *) hci_le_clear_resolving_list,
  (void *) hci_le_read_resolving_list_size,
  (void *) hci_le_read_peer_resolvable_address,
  (void *) hci_le_read_local_resolvable_address,
  (void *) hci_le_set_address_resolution_enable,
  (void *) hci_le_set_resolvable_private_address_timeout,
#endif
#if (CONTROLLER_DATA_LENGTH_EXTENSION_ENABLED == 1)
  (void *) hci_le_read_maximum_data_length,
#endif
#if (CONTROLLER_2M_CODED_PHY_ENABLED == 1)
  (void *) hci_le_read_phy,
  (void *) hci_le_set_default_phy,
  (void *) hci_le_set_phy,
  (void *) hci_le_enhanced_receiver_test,
  (void *) hci_le_enhanced_transmitter_test,
#endif
#if (CONTROLLER_EXT_ADV_SCAN_ENABLED == 1)
  (void *) hci_le_set_advertising_set_random_address,
  (void *) hci_le_set_extended_advertising_parameters,
  (void *) hci_le_set_extended_advertising_enable,
  (void *) hci_le_read_number_of_supported_advertising_sets,
  (void *) hci_le_remove_advertising_set,
  (void *) hci_le_clear_advertising_sets,
  (void *) hci_le_set_periodic_advertising_parameters,
#endif
#if ((CONTROLLER_PERIODIC_ADV_ENABLED == 1) &&\
    (CONTROLLER_EXT_ADV_SCAN_ENABLED == 1))
  (void *) hci_le_set_periodic_advertising_enable,
#endif
#if (CONTROLLER_EXT_ADV_SCAN_ENABLED == 1)
  (void *) hci_le_set_extended_scan_parameters,
  (void *) hci_le_set_extended_scan_enable,
  (void *) hci_le_extended_create_connection,
#endif
#if ((CONTROLLER_PERIODIC_ADV_ENABLED == 1) &&\
    (CONTROLLER_EXT_ADV_SCAN_ENABLED == 1))
  (void *) hci_le_periodic_advertising_create_sync,
  (void *) hci_le_periodic_advertising_create_sync_cancel,
  (void *) hci_le_periodic_advertising_terminate_sync,
  (void *) hci_le_add_device_to_periodic_advertiser_list,
  (void *) hci_le_remove_device_from_periodic_advertising_list,
  (void *) hci_le_clear_periodic_advertiser_list,
  (void *) hci_le_read_periodic_advertiser_list_size,
#endif
  (void *) hci_le_read_transmit_power,
  (void *) hci_le_read_rf_path_compensation,
  (void *) hci_le_write_rf_path_compensation,
#if (CONTROLLER_PRIVACY_ENABLED == 1)
  (void *) hci_le_set_privacy_mode,
#endif
#if (CONTROLLER_CTE_ENABLED == 1)
  (void *) hci_le_receiver_test_v3,
  (void *) hci_le_transmitter_test_v3,
  (void *) hci_le_set_connectionless_cte_transmit_parameters,
  (void *) hci_le_set_connectionless_cte_transmit_enable,
  (void *) hci_le_set_connectionless_iq_sampling_enable,
  (void *) hci_le_set_connection_cte_receive_parameters,
  (void *) hci_le_set_connection_cte_transmit_parameters,
  (void *) hci_le_connection_cte_request_enable,
  (void *) hci_le_connection_cte_response_enable,
  (void *) hci_le_read_antenna_information,
#endif
#if ((CONTROLLER_PERIODIC_ADV_ENABLED == 1) &&\
    (CONTROLLER_EXT_ADV_SCAN_ENABLED == 1))
  (void *) hci_le_set_periodic_advertising_receive_enable,
  (void *) hci_le_periodic_advertising_sync_transfer,
  (void *) hci_le_periodic_advertising_set_info_transfer,
  (void *) hci_le_set_periodic_advertising_sync_transfer_parameters,
  (void *) hci_le_set_default_periodic_advertising_sync_transfer_parameters,
#endif
#if (CONTROLLER_POWER_CONTROL_ENABLED == 1)
  (void *) hci_le_enhanced_read_transmit_power_level,
  (void *) hci_le_read_remote_transmit_power_level,
  (void *) hci_le_set_path_loss_reporting_parameters,
  (void *) hci_le_set_path_loss_reporting_enable,
  (void *) hci_le_set_transmit_power_reporting_enable,
#endif
#if (CONTROLLER_CTE_ENABLED == 1)
  (void *) hci_le_transmitter_test_v4,
#endif
  (void *) aci_hal_get_fw_build_number,
  (void *) aci_hal_write_config_data,
  (void *) aci_hal_read_config_data,
  (void *) aci_hal_set_tx_power_level,
  (void *) aci_hal_le_tx_test_packet_number,
  (void *) aci_hal_tone_start,
  (void *) aci_hal_tone_stop,
  (void *) aci_hal_get_link_status,
  (void *) aci_hal_set_radio_activity_mask,
  (void *) aci_hal_set_event_mask,
#if (CONTROLLER_POWER_CONTROL_ENABLED == 1)
  (void *) aci_hal_set_le_power_control,
#endif
  (void *) aci_hal_get_evt_fifo_max_level,
  (void *) aci_gap_set_io_capability,
  (void *) aci_gap_set_authentication_requirement,
  (void *) aci_gap_pass_key_resp,
  (void *) aci_gap_init,
  (void *) aci_gap_slave_security_req,
  (void *) aci_gap_get_security_level,
  (void *) aci_gap_set_event_mask,
  (void *) aci_gap_terminate,
  (void *) aci_gap_clear_security_db,
  (void *) aci_gap_allow_rebond,
#if (CONTROLLER_MASTER_ENABLED == 1)
  (void *) aci_gap_create_connection,
  (void *) aci_gap_terminate_proc,
  (void *) aci_gap_start_connection_update,
  (void *) aci_gap_send_pairing_req,
#endif
  (void *) aci_gap_resolve_private_addr,
  (void *) aci_gap_get_bonded_devices,
  (void *) aci_gap_is_device_bonded,
#if (SECURE_CONNECTIONS_ENABLED == 1)
  (void *) aci_gap_numeric_comparison_value_confirm_yesno,
  (void *) aci_gap_passkey_input,
#endif
  (void *) aci_gap_get_oob_data,
  (void *) aci_gap_set_oob_data,
  (void *) aci_gap_remove_bonded_device,
  (void *) aci_gap_set_advertising_configuration,
  (void *) aci_gap_set_advertising_enable,
#if (CONTROLLER_MASTER_ENABLED == 1)
  (void *) aci_gap_set_scan_configuration,
  (void *) aci_gap_set_connection_configuration,
  (void *) aci_gap_start_procedure,
  (void *) aci_gap_discover_name,
#endif
  (void *) aci_gap_add_devices_to_white_and_resolving_list,
  (void *) aci_gap_configure_white_and_resolving_list,
#if ((CONTROLLER_PERIODIC_ADV_ENABLED == 1) &&\
    (CONTROLLER_EXT_ADV_SCAN_ENABLED == 1))
  (void *) aci_gap_set_periodic_advertising_configuration,
  (void *) aci_gap_set_periodic_advertising_enable,
  (void *) aci_gap_periodic_advertising_create_sync,
  (void *) aci_gap_periodic_advertising_create_sync_cancel,
#endif
#if (CONTROLLER_EXT_ADV_SCAN_ENABLED == 1)
  (void *) aci_gap_remove_advertising_set,
  (void *) aci_gap_clear_advertising_sets,
#endif
#if ((CONTROLLER_PERIODIC_ADV_ENABLED == 1) &&\
    (CONTROLLER_EXT_ADV_SCAN_ENABLED == 1))
  (void *) aci_gap_periodic_advertising_terminate_sync,
  (void *) aci_gap_add_device_to_periodic_advertiser_list,
  (void *) aci_gap_remove_device_from_periodic_advertising_list,
  (void *) aci_gap_clear_periodic_advertiser_list,
  (void *) aci_gap_read_periodic_advertiser_list_size,
  (void *) aci_gap_set_periodic_advertising_receive_enable,
  (void *) aci_gap_periodic_advertising_sync_transfer,
  (void *) aci_gap_periodic_advertising_set_info_transfer,
  (void *) aci_gap_set_periodic_advertising_sync_transfer_parameters,
  (void *) aci_gap_set_default_periodic_advertising_sync_transfer_parameters,
  (void *) aci_gap_set_periodic_advertising_data,
#endif
  (void *) aci_gap_set_advertising_data,
  (void *) aci_gap_set_scan_response_data,
  (void *) aci_gatt_srv_init,
  (void *) aci_gatt_set_event_mask,
  (void *) aci_gatt_clt_exchange_config,
  (void *) aci_gatt_clt_prepare_write_req,
  (void *) aci_gatt_clt_execute_write_req,
  (void *) aci_gatt_clt_disc_all_primary_services,
  (void *) aci_gatt_clt_disc_primary_service_by_uuid,
  (void *) aci_gatt_clt_find_included_services,
  (void *) aci_gatt_clt_disc_all_char_of_service,
  (void *) aci_gatt_clt_disc_char_by_uuid,
  (void *) aci_gatt_clt_disc_all_char_desc,
  (void *) aci_gatt_clt_read,
  (void *) aci_gatt_clt_read_using_char_uuid,
  (void *) aci_gatt_clt_read_long,
  (void *) aci_gatt_clt_read_multiple_char_value,
  (void *) aci_gatt_clt_write_without_resp,
  (void *) aci_gatt_clt_signed_write_without_resp,
  (void *) aci_gatt_clt_confirm_indication,
  (void *) aci_gatt_srv_notify,
  (void *) aci_gatt_srv_write_multiple_instance_handle_value,
  (void *) aci_gatt_srv_add_service,
  (void *) aci_gatt_srv_include_service,
  (void *) aci_gatt_srv_add_char,
  (void *) aci_gatt_srv_add_char_desc,
  (void *) aci_gatt_srv_rm_service,
  (void *) aci_gatt_srv_rm_include_service,
  (void *) aci_gatt_srv_rm_char,
  (void *) aci_gatt_srv_get_service_handle,
  (void *) aci_gatt_srv_get_include_service_handle,
  (void *) aci_gatt_srv_get_char_decl_handle,
  (void *) aci_gatt_srv_get_descriptor_handle,
  (void *) aci_gatt_srv_read_handle_value,
  (void *) aci_gatt_srv_resp,
  (void *) aci_gatt_clt_write,
  (void *) aci_gatt_clt_write_long,
  (void *) aci_gatt_clt_write_char_reliable,
  (void *) aci_gatt_srv_read_multiple_instance_handle_value,
  (void *) aci_l2cap_connection_parameter_update_req,
#if (CONTROLLER_MASTER_ENABLED == 1)
  (void *) aci_l2cap_connection_parameter_update_resp,
#endif
#if (L2CAP_COS_ENABLED == 1)
  (void *) aci_l2cap_send_flow_control_credits,
  (void *) aci_l2cap_disconnect,
  (void *) aci_l2cap_cfc_connection_req,
  (void *) aci_l2cap_cfc_connection_resp,
  (void *) aci_l2cap_extract_sdu_data,
  (void *) aci_l2cap_transmit_sdu_data,
#endif
  (void *) ll_set_legacy_advertising_data_ptr,
  (void *) ll_set_legacy_scan_reponse_data_ptr,
  (void *) ll_set_advertising_data_ptr,
  (void *) ll_set_scan_reponse_data_ptr,
  (void *) ll_get_advertising_info,
  (void *) ll_set_periodic_advertising_data_ptr,
  (void *) aci_hal_get_anchor_point
};
